name: OnlineMarket
main: com.imyvm.onlinemarket.Main
description: "Provides a sell/buy system and global market."
version: 3.0
depend: [Vault,NyaaCore]
authors: [cyilin, RecursiveG]
website: "https://github.com/NyaaCat/HamsterEcoHelper"

commands:
  onlinemarket:
    description: The command for OnlineMarket
    aliases: om
    permission: heh.command
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand] [Arguments...] or /<command> help"

permissions:
  heh.*:
    description: Base permission node for OnlineMarket
    default: false
    children:
      heh.user: true
      heh.admin: true
  heh.user:
    description: Base permission node for players
    default: true
    children:
      heh.sell: true
      heh.sell.default: true
      heh.view: true
      heh.retrieve: true
      heh.command: true
  heh.admin:
    description: Permission node for operators
    default: op
    children:
      heh.user: true
      heh.debug: true
      heh.giveitem: true